# Data Loading

In [105]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [106]:
df = pd.read_csv("/content/drive/MyDrive/RS Data/challenge 2/zomato.csv")

In [107]:
df.head()

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari

In [108]:
df.shape

(51717, 17)

# Data Preprocessing

In [109]:
data = df[df['rest_type'] == 'Quick Bites']

In [110]:
data

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
31,https://www.zomato.com/bangalore/foodiction-1-...,"2/1, 7th Main, Dwarakangar, Hosakeregalli, Ban...",Foodiction,Yes,No,2.8/5,506,+91 9916107070,Banashankari,Quick Bites,"Burgers, Lassi, Chicken Grill, Naan, Momos, Ch...","North Indian, Fast Food, Chinese, Burger",500,"[('Rated 1.0', ""RATED\n Worst restaurant ever...",[],Delivery,Banashankari
34,https://www.zomato.com/bangalore/faasos-banash...,"80, BDA Complex, 2nd Stage, Banashankari, Bang...",Faasos,Yes,No,4.2/5,415,+91 7700020020,Banashankari,Quick Bites,"Rolls, Veggie Wrap, Chocolate Fantasy, Rice Bo...","North Indian, Biryani, Fast Food",500,"[('Rated 3.0', 'RATED\n Not worth for the mon...","['Chole Kulcha Meal', 'Upvas Aloo Paratha With...",Delivery,Banashankari
36,https://www.zomato.com/bangalore/fast-and-fres...,"32, 7th Main Road, Dwaraka Nagar,Near PES Coll...",Fast And Fresh,Yes,No,2.8/5,91,+91 9742974232,Banashankari,Quick Bites,NaN,"North Indian, Chinese, Fast Food",400,"[('Rated 1.0', 'RATED\n Half baked rice in a ...",[],Delivery,Banashankari
39,https://www.zomato.com/bangalore/maruthi-davan...,"556/A, Water Tank Road, 3rd Stage, Banashankar...",Maruthi Davangere Benne Dosa,Yes,No,4.0/5,17,+91 9019563485,Banashankari,Quick Bites,NaN,South Indian,150,"[('Rated 5.0', ""RATED\n This restaurant serve...","['Benne Dosa', 'Benne Masala Dosa', 'Benne Kal...",Delivery,Banashankari
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51641,https://www.zomato.com/bangalore/andhra-spices...,"188, ITPL Main Road, Brookefields, Bangalore, ...",Andhra Spices,No,No,3.2 /5,4,NaN,Brookefield,Quick Bites,NaN,"Andhra, Chinese, South Indian",NaN,"[('Rated 2.0', ""RATED\n Food is not upto the ...",[],Dine-out,Whitefield
51642,https://www.zomato.com/bangalore/basaveshwara-...,"Nanjudeshwari complex, Oppsite Brookefield Mal...",Basaveshwara Khanavali,No,No,NaN,0,+91 9740912864\n+91 7353747430,Brookefield,Quick Bites,NaN,South Indian,200,[],[],Dine-out,Whitefield
51643,https://www.zomato.com/bangalore/new-ambur-bir...,"AECS Layout, ITPL Main Road, Brookefield, Bang...",New Ambur Biryani,No,No,NaN,0,+91 9443087893,Brookefield,Quick Bites,NaN,"Biryani, Kebab",300,[],[],Dine-out,Whitefield
51644,https://www.zomato.com/bangalore/punjabi-thadk...,"7/3, ASK Tower, Kundanahalli Gate, Next to Bat...",Punjabi Thadka,No,No,NaN,0,+91 7338330336\n+91 9591568221,Brookefield,Quick Bites,NaN,North Indian,400,[],[],Dine-out,Whitefield
51645,https://www.zomato.com/bangalore/raapchick-bro...,"Opposite Brookefield Mall, Kundanhalli, Brooke...",Raapchick,Yes,No,3.6 /5,49,080 41717785\n+91 9571153004,Brookefield,Quick Bites,Burgers,"Fast Food, Burger",300,"[('Rated 5.0', ""RATED\n I was randomly lookin...","['Chicken Wrap', 'Veg Crunch Burger', 'Spicy P...",Dine-out,Whitefield

In [111]:
data1 = data[data['votes']>=50]

In [112]:
data1

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
31,https://www.zomato.com/bangalore/foodiction-1-...,"2/1, 7th Main, Dwarakangar, Hosakeregalli, Ban...",Foodiction,Yes,No,2.8/5,506,+91 9916107070,Banashankari,Quick Bites,"Burgers, Lassi, Chicken Grill, Naan, Momos, Ch...","North Indian, Fast Food, Chinese, Burger",500,"[('Rated 1.0', ""RATED\n Worst restaurant ever...",[],Delivery,Banashankari
34,https://www.zomato.com/bangalore/faasos-banash...,"80, BDA Complex, 2nd Stage, Banashankari, Bang...",Faasos,Yes,No,4.2/5,415,+91 7700020020,Banashankari,Quick Bites,"Rolls, Veggie Wrap, Chocolate Fantasy, Rice Bo...","North Indian, Biryani, Fast Food",500,"[('Rated 3.0', 'RATED\n Not worth for the mon...","['Chole Kulcha Meal', 'Upvas Aloo Paratha With...",Delivery,Banashankari
36,https://www.zomato.com/bangalore/fast-and-fres...,"32, 7th Main Road, Dwaraka Nagar,Near PES Coll...",Fast And Fresh,Yes,No,2.8/5,91,+91 9742974232,Banashankari,Quick Bites,NaN,"North Indian, Chinese, Fast Food",400,"[('Rated 1.0', 'RATED\n Half baked rice in a ...",[],Delivery,Banashankari
40,https://www.zomato.com/bangalore/chaatimes-bas...,"39, 3rd Main,4th Cross, Hanumanth Nagar, Near,...",Chaatimes,Yes,No,3.8/5,133,+91 8884232233,Basavanagudi,Quick Bites,"Dabeli, Faluda, Masala Poori, Sandwiches, Tokr...","Street Food, Fast Food",200,"[('Rated 4.0', 'RATED\n Ordered pack of dabel...",[],Delivery,Banashankari
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51598,https://www.zomato.com/bangalore/the-grilled-f...,"Borwell Road, Bangalore, Whitefield, Bangalore",The Grilled & Fried,Yes,No,3.3 /5,130,+91 9986057577,Whitefield,Quick Bites,"Potato Fries, Chicken Curry",Fast Food,300,"[('Rated 4.0', ""RATED\n This place serves bes...","['Chicken Burger', 'Crispy Fried Chicken', 'Cr...",Dine-out,Whitefield
51601,https://www.zomato.com/bangalore/khan-saheb-gr...,"3/3 - 3/4, Whitefield Main Road, Mahadevapura,...",Khan Saheb Grills and Rolls,Yes,No,3.8 /5,305,+91 8880121121,Whitefield,Quick Bites,"Rolls, Chicken Tikka Roll, Chicken Bhuna Roll,...","Fast Food, Rolls",400,"[('Rated 4.0', 'RATED\n Was there last evenin...","['Tandoori Paneer', 'Tandoori Chicken', 'Tangd...",Dine-out,Whitefield
51602,https://www.zomato.com/bangalore/indian-aroma-...,"201, Nallurhalli Road, Siddapura, Whitefield, ...",Indian Aroma Cafe,Yes,No,2.8 /5,84,+91 7204930881,Whitefield,Quick Bites,NaN,"North Indian, Chinese",300,"[('Rated 1.0', 'RATED\n Had a one of the very...","['Chicken Kabab [5 Pieces]', 'Chilli Chicken',...",Dine-out,Whitefield
51624,https://www.zomato.com/bangalore/slv-grand-itp...,"Satya Sai Complex Hoodi, ITPL Main Road, White...",SLV Grand,Yes,No,3.3 /5,66,+91 7981512319,"ITPL Main Road, Whitefield",Quick Bites,NaN,South Indian,300,"[('Rated 1.0', ""RATED\n Very low quality food...","['Jeera Rice', 'Veg Pulao', 'Veg Biryani', 'Hy...",Dine-out,Whitefield
51629,https://www.zomato.com/bangalore/radha-rani-br...,"Opposite Brookefield Mall, Brookefield, Bangalore",Radha Rani,Yes,No,3.4 /5,252,+91 8792449564\n+91 9886595975,Brookefield,Quick Bites,"Fish, Veg Thali, Biryani","Bengali, North Indian, Chinese",400,"[('Rated 4.0', 'RATED\n One of my favourite b...","['Veg Thali', 'Veg Special Thali', 'Chicken Th...",Dine-out,Whitefield

In [113]:
data1.to_csv("/content/drive/MyDrive/RS Data/challenge 2/Final_resturants.csv")

In [114]:
data2 = data1[['name','online_order','book_table',	"rate", 'location', 'dish_liked',	'cuisines', 'listed_in(type)']]

In [115]:
data2

,name,online_order,book_table,rate,location,dish_liked,cuisines,listed_in(type)
3,Addhuri Udupi Bhojana,No,No,3.7/5,Banashankari,Masala Dosa,"South Indian, North Indian",Buffet
31,Foodiction,Yes,No,2.8/5,Banashankari,"Burgers, Lassi, Chicken Grill, Naan, Momos, Ch...","North Indian, Fast Food, Chinese, Burger",Delivery
34,Faasos,Yes,No,4.2/5,Banashankari,"Rolls, Veggie Wrap, Chocolate Fantasy, Rice Bo...","North Indian, Biryani, Fast Food",Delivery
36,Fast And Fresh,Yes,No,2.8/5,Banashankari,NaN,"North Indian, Chinese, Fast Food",Delivery
40,Chaatimes,Yes,No,3.8/5,Basavanagudi,"Dabeli, Faluda, Masala Poori, Sandwiches, Tokr...","Street Food, Fast Food",Delivery
...,...,...,...,...,...,...,...,...
51598,The Grilled & Fried,Yes,No,3.3 /5,Whitefield,"Potato Fries, Chicken Curry",Fast Food,Dine-out
51601,Khan Saheb Grills and Rolls,Yes,No,3.8 /5,Whitefield,"Rolls, Chicken Tikka Roll, Chicken Bhuna Roll,...","Fast Food, Rolls",Dine-out
51602,Indian Aroma Cafe,Yes,No,2.8 /5,Whitefield,NaN,"North Indian, Chinese",Dine-out
51624,SLV Grand,Yes,No,3.3 /5,"ITPL Main Road, Whitefield",NaN,South Indian,Dine-out
51629,Radha Rani,Yes,No,3.4 /5,Brookefield,"Fish, Veg Thali, Biryani","Bengali, North Indian, Chinese",Dine-out

In [116]:
data2 = data2.dropna()

In [117]:
data2['rating'] = ''
for i in range(len(data2)):

  data2['rating'].iloc[i]  = data2['rate'].iloc[i].split('/')[0]

<ipython-input-117-88f69e825fe3>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2['rating'] = ''
<ipython-input-117-88f69e825fe3>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2['rating'].iloc[i]  = data2['rate'].iloc[i].split('/')[0]

In [118]:
data2.drop(axis="columns",labels=['rate'],inplace=True)

<ipython-input-118-b721310fa4ce>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2.drop(axis="columns",labels=['rate'],inplace=True)

In [119]:
data2.to_csv("/content/drive/MyDrive/RS Data/challenge 2/Final_ready.csv")

In [120]:
data2

,name,online_order,book_table,location,dish_liked,cuisines,listed_in(type),rating
3,Addhuri Udupi Bhojana,No,No,Banashankari,Masala Dosa,"South Indian, North Indian",Buffet,3.7
31,Foodiction,Yes,No,Banashankari,"Burgers, Lassi, Chicken Grill, Naan, Momos, Ch...","North Indian, Fast Food, Chinese, Burger",Delivery,2.8
34,Faasos,Yes,No,Banashankari,"Rolls, Veggie Wrap, Chocolate Fantasy, Rice Bo...","North Indian, Biryani, Fast Food",Delivery,4.2
40,Chaatimes,Yes,No,Basavanagudi,"Dabeli, Faluda, Masala Poori, Sandwiches, Tokr...","Street Food, Fast Food",Delivery,3.8
42,McDonald's,Yes,No,Banashankari,"Burgers, Fries, Hot Chocolate","Burger, Fast Food",Delivery,3.9
...,...,...,...,...,...,...,...,...
51590,U.P. Dhaba,Yes,No,Whitefield,"Paratha, Paneer Thali, Tandoori Roti, Chole Bh...","North Indian, Chinese",Dine-out,2.8
51594,Aryan's Kitchen,Yes,No,Whitefield,"Chaat, Burgers","North Indian, Fast Food",Dine-out,3.1
51598,The Grilled & Fried,Yes,No,Whitefield,"Potato Fries, Chicken Curry",Fast Food,Dine-out,3.3
51601,Khan Saheb Grills and Rolls,Yes,No,Whitefield,"Rolls, Chicken Tikka Roll, Chicken Bhuna Roll,...","Fast Food, Rolls",Dine-out,3.8
51629,Radha Rani,Yes,No,Brookefield,"Fish, Veg Thali, Biryani","Bengali, North Indian, Chinese",Dine-out,3.4

In [121]:
data2['features'] = data2['location'] + ' ' + data2['dish_liked'] + ' ' + data2['cuisines'] + ' ' + data2['listed_in(type)']

<ipython-input-121-7629aa1b2e65>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2['features'] = data2['location'] + ' ' + data2['dish_liked'] + ' ' + data2['cuisines'] + ' ' + data2['listed_in(type)']

In [122]:
data2

,name,online_order,book_table,location,dish_liked,cuisines,listed_in(type),rating,features
3,Addhuri Udupi Bhojana,No,No,Banashankari,Masala Dosa,"South Indian, North Indian",Buffet,3.7,"Banashankari Masala Dosa South Indian, North I..."
31,Foodiction,Yes,No,Banashankari,"Burgers, Lassi, Chicken Grill, Naan, Momos, Ch...","North Indian, Fast Food, Chinese, Burger",Delivery,2.8,"Banashankari Burgers, Lassi, Chicken Grill, Na..."
34,Faasos,Yes,No,Banashankari,"Rolls, Veggie Wrap, Chocolate Fantasy, Rice Bo...","North Indian, Biryani, Fast Food",Delivery,4.2,"Banashankari Rolls, Veggie Wrap, Chocolate Fan..."
40,Chaatimes,Yes,No,Basavanagudi,"Dabeli, Faluda, Masala Poori, Sandwiches, Tokr...","Street Food, Fast Food",Delivery,3.8,"Basavanagudi Dabeli, Faluda, Masala Poori, San..."
42,McDonald's,Yes,No,Banashankari,"Burgers, Fries, Hot Chocolate","Burger, Fast Food",Delivery,3.9,"Banashankari Burgers, Fries, Hot Chocolate Bur..."
...,...,...,...,...,...,...,...,...,...
51590,U.P. Dhaba,Yes,No,Whitefield,"Paratha, Paneer Thali, Tandoori Roti, Chole Bh...","North Indian, Chinese",Dine-out,2.8,"Whitefield Paratha, Paneer Thali, Tandoori Rot..."
51594,Aryan's Kitchen,Yes,No,Whitefield,"Chaat, Burgers","North Indian, Fast Food",Dine-out,3.1,"Whitefield Chaat, Burgers North Indian, Fast F..."
51598,The Grilled & Fried,Yes,No,Whitefield,"Potato Fries, Chicken Curry",Fast Food,Dine-out,3.3,"Whitefield Potato Fries, Chicken Curry Fast Fo..."
51601,Khan Saheb Grills and Rolls,Yes,No,Whitefield,"Rolls, Chicken Tikka Roll, Chicken Bhuna Roll,...","Fast Food, Rolls",Dine-out,3.8,"Whitefield Rolls, Chicken Tikka Roll, Chicken ..."
51629,Radha Rani,Yes,No,Brookefield,"Fish, Veg Thali, Biryani","Bengali, North Indian, Chinese",Dine-out,3.4,"Brookefield Fish, Veg Thali, Biryani Bengali, ..."

In [123]:
for i in range(len(data2)):
  data2["features"].iloc[i]=data2["features"].iloc[i].replace(",","")
  data2["features"].iloc[i]= data2["features"].iloc[i].lower()

<ipython-input-123-446ba4f27ff6>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2["features"].iloc[i]=data2["features"].iloc[i].replace(",","")
<ipython-input-123-446ba4f27ff6>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2["features"].iloc[i]= data2["features"].iloc[i].lower()

In [124]:
data2

,name,online_order,book_table,location,dish_liked,cuisines,listed_in(type),rating,features
3,Addhuri Udupi Bhojana,No,No,Banashankari,Masala Dosa,"South Indian, North Indian",Buffet,3.7,banashankari masala dosa south indian north in...
31,Foodiction,Yes,No,Banashankari,"Burgers, Lassi, Chicken Grill, Naan, Momos, Ch...","North Indian, Fast Food, Chinese, Burger",Delivery,2.8,banashankari burgers lassi chicken grill naan ...
34,Faasos,Yes,No,Banashankari,"Rolls, Veggie Wrap, Chocolate Fantasy, Rice Bo...","North Indian, Biryani, Fast Food",Delivery,4.2,banashankari rolls veggie wrap chocolate fanta...
40,Chaatimes,Yes,No,Basavanagudi,"Dabeli, Faluda, Masala Poori, Sandwiches, Tokr...","Street Food, Fast Food",Delivery,3.8,basavanagudi dabeli faluda masala poori sandwi...
42,McDonald's,Yes,No,Banashankari,"Burgers, Fries, Hot Chocolate","Burger, Fast Food",Delivery,3.9,banashankari burgers fries hot chocolate burge...
...,...,...,...,...,...,...,...,...,...
51590,U.P. Dhaba,Yes,No,Whitefield,"Paratha, Paneer Thali, Tandoori Roti, Chole Bh...","North Indian, Chinese",Dine-out,2.8,whitefield paratha paneer thali tandoori roti ...
51594,Aryan's Kitchen,Yes,No,Whitefield,"Chaat, Burgers","North Indian, Fast Food",Dine-out,3.1,whitefield chaat burgers north indian fast foo...
51598,The Grilled & Fried,Yes,No,Whitefield,"Potato Fries, Chicken Curry",Fast Food,Dine-out,3.3,whitefield potato fries chicken curry fast foo...
51601,Khan Saheb Grills and Rolls,Yes,No,Whitefield,"Rolls, Chicken Tikka Roll, Chicken Bhuna Roll,...","Fast Food, Rolls",Dine-out,3.8,whitefield rolls chicken tikka roll chicken bh...
51629,Radha Rani,Yes,No,Brookefield,"Fish, Veg Thali, Biryani","Bengali, North Indian, Chinese",Dine-out,3.4,brookefield fish veg thali biryani bengali nor...

# Creating Feature Vectors

In [125]:
import nltk
from nltk.tokenize import word_tokenize
nltk.download('punkt')
tokenized_features = [word_tokenize(x) for x in data2["features"]]

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [126]:
import gensim
model = gensim.models.Word2Vec(tokenized_features, vector_size=300, window=5, min_count=1, workers=8)
# Access the word vectors
word_vectors = model.wv

In [127]:
place_review_array = []
for i in range(len(data2['features'])):
  word_vector = np.zeros((1,300))
  for word in word_tokenize(data2['features'].iloc[i]):
    
    word_vector += word_vectors[word]
  word_vector = word_vector/len(word_tokenize(data2['features'].iloc[i]))
  place_review_array.append(word_vector)

In [128]:
place_review_array = np.array(place_review_array)
place_review_array = place_review_array.reshape(-1,300)
place_review_array.shape

(4815, 300)

# Recommendation System (Content Based)

In [139]:
def Recommend():
  user_review = str(input("Enter your query: "))
  print("\n")
  user_review = user_review.lower()
  user_review_array = np.zeros((1, 300))
  for word in word_tokenize(user_review):
    if word in word_vectors:
      user_review_array += word_vectors[word]
    
  user_review_array = user_review_array/len(user_review)
  similarities = cosine_similarity(place_review_array,user_review_array).flatten()
  data2['Similarity'] = similarities
  df=data2.sort_values('Similarity',ascending=False)
  df = df.drop_duplicates(subset=['name'])
  return df

In [144]:
import warnings
warnings.filterwarnings('ignore')

df = Recommend()
display(df.head(5))

Enter your query: I want to eat pizza

,name,online_order,book_table,location,dish_liked,cuisines,listed_in(type),rating,features,Similarity
14757,Pizza Stop,Yes,No,Banaswadi,"Garlic Bread, Nachos, Pasta, Thin Crust Pizza,...","Pizza, Italian",Delivery,3.8,banaswadi garlic bread nachos pasta thin crust...,0.993142
25318,Crunch Pizzas,Yes,No,Banaswadi,"Pepperoni, Cheesy Pizza","Italian, Pizza",Delivery,2.6,banaswadi pepperoni cheesy pizza italian pizza...,0.980925
18865,Domino's Pizza,Yes,No,Indiranagar,"Pane Pizza, Garlic Bread, Pepperoni Pizza, Cho...","Pizza, Fast Food",Dine-out,3.0,indiranagar pane pizza garlic bread pepperoni ...,0.979859
6945,Pizza Hut,Yes,No,"ITPL Main Road, Whitefield","Pane Pizza, Garlic Bread, Thin Crust Pizza, Pa...",Pizza,Delivery,3.7,itpl main road whitefield pane pizza garlic br...,0.976666
8412,La Pino'z Pizza,Yes,No,Koramangala 4th Block,"Fries, White Sauce Pasta, Monster Pizza, Chees...","Italian, Pizza, Beverages",Delivery,4.1,koramangala 4th block fries white sauce pasta ...,0.976386

In [145]:
df = Recommend()
display(df.head(5))

Enter your query: I want to drink coffee

,name,online_order,book_table,location,dish_liked,cuisines,listed_in(type),rating,features,Similarity
2869,By 2 Coffee,Yes,No,Basavanagudi,"Kharabath, Filter Coffee, Idli Vada, Crispy Va...",South Indian,Delivery,4.3,basavanagudi kharabath filter coffee idli vada...,0.981676
20604,South Kitchen,Yes,No,Basavanagudi,"Kharabath, Crispy Vada, Filter Coffee, Idli Va...",South Indian,Delivery,4.3,basavanagudi kharabath crispy vada filter coff...,0.978819
643,Sri Laxmi Venkateshwara Coffee Bar,No,No,Banashankari,"Masala Dosa, Idli Chutney, Kharabath, Filter C...",South Indian,Dine-out,4.4,banashankari masala dosa idli chutney kharabat...,0.977876
802,Mahalaxmi Tiffin Room,No,No,Basavanagudi,"Filter Coffee, Rava Idli, Kali Dosa, Carrot Ha...",South Indian,Dine-out,4.1,basavanagudi filter coffee rava idli kali dosa...,0.976707
3386,Hotel Janatha,No,No,Basavanagudi,"Masala Dosa, Rava Dosa, Khali Dosa, Vada, Filt...",South Indian,Dine-out,4.1,basavanagudi masala dosa rava dosa khali dosa ...,0.976249

In [132]:
df = Recommend()
display(df.head(5))

Enter your query: Masala dosa

<ipython-input-129-6eb139529b7b>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2['Similarity'] = similarities

,name,online_order,book_table,location,dish_liked,cuisines,listed_in(type),rating,features,Similarity
40313,HVR Veg,Yes,No,Seshadripuram,"Vada, Masala Idli, Benne Khali Dosa, Benne Mas...",South Indian,Dine-out,4.5,seshadripuram vada masala idli benne khali dos...,0.992956
39179,Lakshmi Natraja Refreshments,No,No,Majestic,"Podi Masala Dosa, Crispy Masala Dosa, Idli, Va...",South Indian,Dine-out,4.3,majestic podi masala dosa crispy masala dosa i...,0.991717
48615,Lakshmi Natraja Refreshments,No,No,Majestic,"Podi Masala Dosa, Crispy Masala Dosa, Idli, Va...",South Indian,Dine-out,4.3,majestic podi masala dosa crispy masala dosa i...,0.991717
18856,Mavalli Tiffin Room (MTR),No,No,Indiranagar,"Masala Dosa, Filter Coffee, Lunch Thali, Rava ...",South Indian,Dine-out,4.3,indiranagar masala dosa filter coffee lunch th...,0.990447
649,Janahaar,Yes,No,Banashankari,"Masala Dosa, Idli, Filter Coffee, Medu Dosa",South Indian,Dine-out,3.8,banashankari masala dosa idli filter coffee me...,0.990270